### PR TITLE
[Android & iOS] Support of `window.print()` function

### PR DESCRIPTION
**Pull request by birdofpreyru**
https://github.com/react-native-webview/react-native-webview/issues/3317

### CODE REVIEW

**Comment by scamp81** [comment]
Would love to see this applied.  We've been fighting this printing issue on ios for a while.

**Comment by birdofpreyru** [comment]
@scamp81 Unfortunately, I can't say yet it completely works on iOS &mdash; I still haven't figured out how, and whether it is possible to print there the entire page, rather than just the visible WebView viewport. On macOS I kind of found a way to make it work, but that goes against Apple docs on how snapshot config is supposed to work, and it does not work the same on iOS, so... perhaps I overlooked something and I neither have a good solution for macOS.

**Comment by birdofpreyru** [comment]
**Update:** Now it feels I have figured out the right way to do the printing on iOS. Turns out to be quite straightforward, but not easy to figure out starting from WKWebView documentation, neither I saw that right solution in StackOverflow answers to the writing questions :( The PR is updated accordingly.

**Comment by frontendguru1** [comment]
Hi @birdofpreyru 
I am encountering the same issue in one of my projects where I need to open the print preview, allowing the user to print or download the file as a PDF.

As far as I can see, this PR is still pending merging.

**Comment by frontendguru1** [comment]
Hi @jamonholmgren @Titozzz 
Could you please approve and merge PR?

**Comment by frontendguru1** [comment]
Yes, I am also planning to switch to updated version.

Have you published this to NPM?

**Comment by birdofpreyru** [comment]
> Have you published this to NPM?

Yeap.

**Comment by frontendguru1** [comment]
Cool

Could you please share the URL of this?

**Comment by birdofpreyru** [comment]
https://www.npmjs.com/package/@dr.pogodin/react-native-webview

**Comment by frontendguru1** [comment]
Thanks!

**Comment by sgtpsibin** [comment]
@Titozzz  could you please review this PR?

**Comment by yashwanthsandeep** [comment]
@birdofpreyru 
Thanks for the fix, its working in both android and iOS. 
@author Please help review the PR, thank you

**Comment by birdofpreyru** [comment]
Right, **bot**, three months later maintainers still haven’t found time to merge in my PR; in the meantime I’ve already started [my fork of this library](https://www.npmjs.com/package/@dr.pogodin/react-native-webview) &mdash; a few steps ahead of the upstream, and could be even better, if anybody backed me up financially.

**Comment by crstnn** [comment]
@Titozzz @jamonholmgren are there any reservations about merging this PR?

**Review by crstnn — APPROVED** [review]

**Pull request closed without merging**
