### PR TITLE
Make WKWebView inspectable on platforms with inspectable flag

### PR DESCRIPTION
**Pull request by jeremywiebe**
## Summary:

In iOS 16.4/macOS 13.3/tvOS 16.4 Apple added a new flag to WKWebView (named `isInspectable` (Swift), `inspectable` (Objective C)). This flag defaults to false which now disallows inspecting the webview.  Details here: https://webkit.org/blog/13936/enabling-the-inspection-of-web-content-in-apps/

This PR fixes the WKWebView's created in this project so that they're inspectable when the `DEBUG` flag is set.

Fixes: #2914

## Test plan:

I verified this change by installing the `react-native-webview` npm package into an existing project that I had and then applying the changes in this PR to the code in `node_modules/react-native-webview`. 

I then ran my app and navigated to one of the web views. I was able to see the web view in the Safari Debug menu and attach to it.

### CODE REVIEW

**Comment by Tom-Bury** [comment]
Hi! I just opened a similar PR https://github.com/react-native-webview/react-native-webview/pull/2937 where this is behind a prop toggle & also has effect on Android.

From your changes, seems like I'm missing some checks to make things compile well on Xcode < 14.3. I'm not that well with Objective C, you think I could just add these same checks in both places where the `inspectable` bit is used?

**Comment by jeremywiebe** [comment]
> es where t



> Hi! I just opened a similar PR #2937 where this is behind a prop toggle & also has effect on Android.
> 
> From your changes, seems like I'm missing some checks to make things compile well on Xcode < 14.3. I'm not that well with Objective C, you think I could just add these same checks in both places where the `inspectable` bit is used?

Hi @Tom-Bury Feel free to take what you need out of this PR into yours.  Happy for this to get fixed no matter who's PR it's in.  😄

**Comment by frags51** [comment]
@Titozzz @jamonholmgren Kindly review this PR.

**Comment by jeremywiebe** [comment]
@Titozzz @jamonholmgren Is there anything I can do to help move this PR along? 😄

**Comment by Titozzz** [comment]
I merged #2937

**Pull request closed without merging**
