### PR TITLE
[Android] Sends cookies with resource requests (replace PR 1534)

### PR DESCRIPTION
**Pull request by Zaidos9**
[**Replacing PR 1534**](https://github.com/react-native-webview/react-native-webview/pull/1534)
To attach cookie with all resource requests for the page loaded

# Summary

- This PR solves this feature request #1532

- How did you implement the solution?
I implemented this solution by adding a map for storing cookies for authority name and overriding the shouldInterceptRequest callback in RNCWebViewClient.

- What areas of the library does it impact?
RNCWebViewManager, RNCWebViewClient

## Compatibility
| OS | Implemented |
| Android |✅|

## Checklist
- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in README.md
- [ ] I mentioned this change in CHANGELOG.md
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (example/App.js)

### CODE REVIEW

**Comment by Zaidos9** [comment]
@jamonholmgren Created this PR to replace [PR 1534: [Android] Sends cookies with resource requests](https://github.com/react-native-webview/react-native-webview/pull/1534). There we merge conflicts with PR 1534, and I didn't had access to resolve them. Kindly have a look at this new PR.

**Comment by jamonholmgren** [comment]
Thanks @Zaidos9!

Do you see any opportunities to update the documentation in the `./docs` folder for this PR?

**Review by jamonholmgren — DISMISSED** [review]

**Comment by Zaidos9** [comment]
@jamonholmgren Updated the doc with a line on cookie management for Android. Kindly have a look.

**Comment by Zaidos9** [comment]
@jamonholmgren There seems to be Test failure for Windows CI. The failing command looks to be `yarn test:windows` and is failing for `master` branch and multiple PRs as well. Is this a known issue?

**Review by Titozzz — APPROVED** [review]

**Review by Titozzz — CHANGES_REQUESTED** [review]
What if the webpage modify / destroy cookies ? It looks like they would still be in the map and sent inside the next requests

**Comment by jamonholmgren** [comment]
Also, could you provide a test plan for this? How would we test that this works (and that the current version does _not_ work)?

**Pull request closed without merging**
