### PR TITLE
Fix clearCache link in index

### PR DESCRIPTION
**Pull request by Reisclef**
The id for the clearCache method is clearCachebool, but the index was incorrectly only referencing clearCache.

### CODE REVIEW

**Review by TheAlmightyBob — CHANGES_REQUESTED** [review]
Thanks! Would you mind updating the Portuguese version while you're at it? Looks like it has the same issue

**Comment by Reisclef** [comment]
Sure thing! Let me know if there's anything else. :)

**Review by TheAlmightyBob — APPROVED** [review]

**Comment by TheAlmightyBob** [comment]
Argh. Obviously the CI failure is unrelated to your change... I'm _guessing_ it's a break from using the latest XCode version... (possibly combined with not using the latest version of react-native-macos)

**Comment by Reisclef** [comment]
Thanks for merging back in the most recent changes @TheAlmightyBob . 👍

**Pull request merged**
