### PR TITLE
Support File Input On Macos

### PR DESCRIPTION
**Pull request by 17Amir17**
Support File Input On MacOS #2633, by implementing https://developer.apple.com/documentation/webkit/wkopenpanelparameters?language=objc

This requires `User Selected File` read permission otherwise will crash when attempting to open file input

Screen Shot 2022-11-08 at 12 28 32

### CODE REVIEW

**Comment by amilich** [comment]
Hey all! Would love to get this merged.

**Comment by 17Amir17** [comment]
@Titozzz You can test this by changing the url in the example app to `imgur` or some other website with a file input and check if it opens.

**Comment by amilich** [comment]
Any way to update this and get it in?

**Comment by amilich** [comment]
@Titozzz @jamonholmgren any way we can merge this?

**Comment by amilich** [comment]
Is this actively maintained?

**Comment by TheAlmightyBob** [comment]
> You can test this by changing the url in the example app to imgur or some other website with a file input and check if it opens

There is an existing file upload page in the example app, but it is currently only enabled for Android (via `Platform.OS` check in `App.tsx`). Can that be used for MacOS with this change?

**Comment by 17Amir17** [comment]
> There is an existing file upload page in the example app, but it is currently only enabled for Android (via `Platform.OS` check in `App.tsx`). Can that be used for MacOS with this change?

Yup! I'll update it

Screenshot 2022-12-07 at 17 43 33

**Review by TheAlmightyBob — APPROVED** [review]

**Pull request merged**
