### PR TITLE
fix(iOS): enable loading WebView even when off screen

### PR DESCRIPTION
**Pull request by goleary**
This is a revival of  #813 (thanks @philippeauriach)

Requests for this functionality:
#696 
#971 

I must admit that I'm developing on Windows so I haven't tested this...I just repeated the commit from #813 in the latest of this repo hoping that CI would help test and/or a generous Mac user could help verify this works as expected.

### CODE REVIEW

**Comment by pkieltyka** [comment]
please review when folks are free, its a nice one

**Comment by goleary** [comment]
fwiw I got someone on my team with a mac to try this out and it didn't work.

I should be getting a mac within a couple months, but until then any charitable mac users are welcome to pick this up 😁

**Comment by gbhrdt** [comment]
@goleary  FYI I just checked this PR on my mac and it works fine on the lastest iOS version! Feel free to re-open maybe :-)

**Comment by walterholohan** [comment]
Was version of this fix ever merged into master and released?

**Comment by gbhrdt** [comment]
@walterholohan  afaik this is not merged to master, yet.

**Comment by finalight** [comment]
are we going to create a PR to merge it to master?

**Comment by ladp333** [comment]
https://github.com/react-native-webview/react-native-webview/pull/3615#issuecomment-3070819578

**Pull request closed without merging**
