### PR TITLE
‼️ Repro for Android libhwui crash (💸 $500 bounty for fix)

### PR DESCRIPTION
**Pull request by andreialecu**
This extremely worrying bug doesn't seem to get much attention.

Mainly reported at #1915, but also in various issues:
#2282 
#2494 
#1838 
#2716 

I managed to make a simple repro for it.

Here's a recording of the crash:

https://user-images.githubusercontent.com/697707/205442080-c90a796f-f323-4637-b34e-e906c5e5d77a.mov

Crash log:

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

Unknown

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

Build fingerprint: 'google/sdk_gphone64_arm64/emulator64_arm64:12/S2B1.211112.006/7934767:userdebug/dev-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-12-03 16:59:06.855918938+0200
Process uptime: 0s
Cmdline: com.microsoft.reacttestapp
pid: 30354, tid: 30393, name: RenderThread  >>> com.microsoft.reacttestapp <<<
uid: 10148
tagged_addr_ctrl: 0000000000000001
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x20
Cause: null pointer dereference
    x0  0000000000000000  x1  00000074df618770  x2  0000000000000000  x3  0000000000000000
    x4  0000000000000078  x5  00000000000003b4  x6  000000000000056b  x7  0000000000000000
    x8  0000000000000000  x9  0000000000000000  x10 0000000000000000  x11 0000000200000004
    x12 0000000000000000  x13 00000074df4525c8  x14 00000074df75038c  x15 000000000000002e
    x16 00000074dbff27d0  x17 00000074d9bb6b40  x18 00000071a598c000  x19 0000000000000000
    x20 0000000000000000  x21 0000000000000000  x22 0000000000000000  x23 0000000000000000
    x24 0000000000000000  x25 0000000000000000  x26 0000000000000000  x27 0000000000000000
    x28 0000000000000000  x29 00000071a995d5e0
    lr  00000074df8ed81c  sp  00000071a995d5e0  pc  00000074df8096ac  pst 0000000020001000
backtrace:
      #00 pc 00000000004096ac  /system/lib64/libhwui.so (SkSurface::getCanvas()+16) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #01 pc 00000000004ed818  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::GLFunctorDrawable::onDraw(SkCanvas*)+1604) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #02 pc 00000000004be930  /system/lib64/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+88) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #03 pc 000000000023ec80  /system/lib64/libhwui.so (SkGpuDevice::drawDrawable(SkDrawable*, SkMatrix const*, SkCanvas*)+360) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #04 pc 00000000004cb7d8  /system/lib64/libhwui.so (android::uirenderer::$_36::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.15275904245672009312)+128) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #05 pc 00000000002f7160  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+2820) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #06 pc 00000000002f64ec  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+236) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #07 pc 000000000028376c  /system/lib64/libhwui.so (android::uirenderer::$_23::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.15275904245672009312)+84) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #08 pc 00000000002f7160  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+2820) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #09 pc 00000000002f64ec  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+236) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #10 pc 000000000028376c  /system/lib64/libhwui.so (android::uirenderer::$_23::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.15275904245672009312)+84) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #11 pc 00000000002f7160  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+2820) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #12 pc 00000000002f64ec  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*)+236) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #13 pc 000000000028376c  /system/lib64/libhwui.so (android::uirenderer::$_23::__invoke(void const*, SkCanvas*, SkMatrix const&) (.llvm.15275904245672009312)+84) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #14 pc 00000000002f7160  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+2820) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #15 pc 0000000000309c70  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*) const+196) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #16 pc 000000000034f1b8  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderLayersImpl(android::uirenderer::LayerUpdateQueue const&, bool)+776) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #17 pc 000000000034c7a0  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrame(android::uirenderer::LayerUpdateQueue const&, SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, bool, android::uirenderer::Rect const&, sk_sp<SkSurface>, SkMatrix const&)+132) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #18 pc 000000000034c308  /system/lib64/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::draw(android::uirenderer::renderthread::Frame const&, SkRect const&, SkRect const&, android::uirenderer::LightGeometry const&, android::uirenderer::LayerUpdateQueue*, android::uirenderer::Rect const&, bool, android::uirenderer::LightInfo const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, android::uirenderer::FrameInfoVisualizer*)+432) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #19 pc 00000000003baac0  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+1116) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #20 pc 00000000003b9730  /system/lib64/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c1671e787f244890c877724752face20+596) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #21 pc 00000000003c64d4  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+156) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #22 pc 00000000003c6240  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+84) (BuildId: 85798ac783f1b180d1c434f08541e0b4)
      #23 pc 00000000000120ac  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+260) (BuildId: 5b16e5a0d014fea15568edac54941124)
      #24 pc 0000000000011964  /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*)+404) (BuildId: 5b16e5a0d014fea15568edac54941124)
      #25 pc 00000000000b1810  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264) (BuildId: cff0d514715347e982aad7cd88a43ce8)
      #26 pc 00000000000512f0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: cff0d514715347e982aad7cd88a43ce8)
```

Screenshot of crash in Flipper:

Screenshot 2022-12-03 at 15 00 24

### CODE REVIEW

**Comment by andreialecu** [comment]
One thing to note is that setting `androidLayerType="software"` prevents the crash, but results in other potential issues as noted in previous threads.

**Comment by andreialecu** [comment]
More related issues: 

https://github.com/invertase/react-native-firebase/issues/2935
https://github.com/react-native-webview/react-native-webview/pull/854
https://github.com/react-native-webview/react-native-webview/issues/575
https://github.com/wix/react-native-navigation/issues/5702

Still getting this crash in production. 

`androidLayerType="software"` makes larger content render blank/transparent so it is not a solution.

It appears that wrapping the webview in another View with `renderToHardwareTextureAndroid={true}` helps a bit for some cases, but I can still reproduce some crashes.

Getting this crash in a real app just due to navigation, without interacting with scrollviews. For the navigation case, `renderToHardwareTextureAndroid` does not help.

**Comment by andreialecu** [comment]
There's also a repro linked here: https://github.com/react-navigation/react-navigation/issues/9755

**Comment by andreialecu** [comment]
## I'll contribute $500 (via GitHub sponsors, preferably) to whoever can fix this crash once and for all. 

No workarounds, please, just a native fix of some sort. It also has to fix the other cases related to navigation that are mentioned in other threads.

**Comment by hungvu193** [comment]
Have you fixed this? @andreialecu 
I can only make it work if I use navigation listener 'transitionEnd' and 'transitionEnd'.
Only load webview after  `transitionEnd` and remove it when `transitionEnd`.

```javascript
const [isInteractEnd, setIsInteractEnd] = React.useState(false);
  React.useEffect(() => {
    const unsubscribe = navigation.addListener('transitionEnd', () => {
      // do something
      setIsInteractEnd(true);
    });

    return unsubscribe;
  }, [navigation]);

  React.useEffect(() => {
    const unsubscribe = navigation.addListener('beforeRemove', () => {
      // do something
      setIsInteractEnd(false);
    });

{isInteractEnd && <Webview />

```

**Comment by andreialecu** [comment]
This is finally fixed by #2874, so I'll close this repro. See the discussion there.

**Comment by Liguoju** [comment]
niu bi

**Pull request closed without merging**
