### PR TITLE
README fixes: badge, minor wording tweaks

### PR DESCRIPTION
**Pull request by jamonholmgren**
Pretty tiny updates to the README.

### CODE REVIEW

**Review by TheAlmightyBob — APPROVED** [review]

**Comment by TheAlmightyBob** [comment]
@jamonholmgren @Titozzz While the [failure of the "publish" CI job](https://app.circleci.com/pipelines/github/react-native-webview/react-native-webview/3174/workflows/a70dead8-d36a-4272-bf34-17a9f8b8d051/jobs/5776) doesn't matter for this particular PR, it seems like something that will need to be fixed before any new version can be released...?

Error is "Invalid GitHub token."

**Comment by jamonholmgren** [comment]
I updated the GH_TOKEN "personal access token" to one of the new "fine-grained personal access tokens". Seeing if that is working now.

CleanShot 2023-03-06 at 18 03 35@2x

https://github.com/settings/personal-access-tokens/new

Note I needed to allow this within the `react-native-webview` organization, as it's not available by default.

**Comment by jamonholmgren** [comment]
So, that didn't work.

```
[2:10:27 AM] [semantic-release] › ✖  The command "git push --dry-run https://[secure]@github.com/react-native-webview/react-native-webview.git HEAD:master" failed with the error message remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/react-native-webview/react-native-webview.git/'
```

I can't add a classic "personal access token" for my own account as it has access to sensitive repos. It appears this fine-grained PAT isn't working properly. Ideas, @Titozzz ?

**Comment by TheAlmightyBob** [comment]
Hm. I see that the error you quoted was there in the original failure too, I just didn't think it was as significant as the "invalid token" error.

It looks like your change _did_ resolve the invalid token error at least, so.... progress??? (unless that one was a red herring?)

I wonder if upgrading `semantic-release` might help....? ¯\\\_(ツ)\_/¯

**Comment by Titozzz** [comment]
Nothing to worry about, I just used an expiring token following the new security recommandations. I'll update it before the next release. Hopefully soon, I did a new RC yesterday for new arch. If all good I'll prod

**Comment by jamonholmgren** [comment]
@Titozzz TY!

**Pull request merged**
