### PR TITLE
[Add] Prop autoShowKeyboard to prevent keyboard from showing

### PR DESCRIPTION
**Pull request by remarket-vn**
Issue related #1650

### CODE REVIEW

**Review by jamonholmgren — COMMENTED** [review]
Looks great. Can you update the documentation too?

**Comment by jamonholmgren** [comment]
Additionally, can you _only_ add the listener if the property is enabled, and remove the listener if it's not needed? The listener should really only run if `autoShowKeyboard` is set to `false`.

**Comment by aland96** [comment]
I'm interested in this feature, it would be handy in cases where a custom keyboard is already used within the webview.

**Comment by R-iskey** [comment]
Why it's closed, what's the problem with that?

**Pull request closed without merging**
