### PR TITLE
fix(android): add onDownloadUnsupportedURL to handle android crash when download blob or base64 link

### PR DESCRIPTION
**Pull request by twisger**
There are lots of crash issues in android is caused by download a link not http protocol,so add a event to handle it and pass it to js layer.If necceary,it can be resolved further in the js handler.

related issue :#1090,#1760,#1945, #2073,#2078
related PR: #1546,#1817,#2065

### CODE REVIEW

**Comment by KaungHtetHein116** [comment]
did anyone find solution yet?

**Comment by twisger** [comment]
> did anyone find solution yet?

I'm working on making the blob and base64 link works well, but there are some file write permission issue need to be resolved in android 10.

**Comment by rameshpatel79** [comment]
@twisger , 

Will this handle the issue mentioned at: https://github.com/react-native-webview/react-native-webview/issues/1914?

Also, you mentioned "I also have to fetch the blob in JS of webview" at https://github.com/react-native-webview/react-native-webview/pull/1817#issuecomment-795795135. Can you please tell how to do that? I want to catch the blob response when user clicks on a button that downloads blob file. Very simple sample here: https://snack.expo.io/@rameshpatell79/react-native-webview-download-error

**Comment by twisger** [comment]
> @twisger ,
> 
> Will this handle the issue mentioned at: #1914?
> 
> Also, you mentioned "I also have to fetch the blob in JS of webview" at [#1817 (comment)](https://github.com/react-native-webview/react-native-webview/pull/1817#issuecomment-795795135). Can you please tell how to do that? I want to catch the blob response when user clicks on a button that downloads blob file. Very simple sample here: https://snack.expo.io/@rameshpatell79/react-native-webview-download-error

@rameshpatel79 It will not be handled because it it not a url cause crash. The code can fetch blob is like blow:




```
const getCodeOfFetchBlob = (url: string) => `
(function(){
    fetch("${url}").then(function(res) {
      var reader = new FileReader()
      res.blob().then(function(blob) {
        reader.readAsDataURL(blob)
        reader.onload = function() {
          window.ReactNativeWebView.postMessage(JSON.stringify({
            event: 'blob',
            payload: {
              uri: this.result
            }
          }))
        }
      })
    })
})();
```
If need keep compatible with lower version webView, the `fetch` should be replaced to `xhr`.

**Comment by smarano** [comment]
I have found and tested a simple working solution to download "**blob:http://**" urls.
I realized that the binary content of the url 'ahead' of the "blob:" prefix has still valid downloadable content. 
The working solution is to simply remove the "blob:" prefix in the onDownloadStart() method.
In addition, for prefixes other than "blob:", just return and avoid the crash.

```
// file RNCWebViewManager.java
 webView.setDownloadListener(new DownloadListener() {
      public void onDownloadStart(String url, String userAgent, String contentDisposition, String mimetype, long contentLength) {

	// check unsupported urls
	if (!url.startsWith("http")) {   
          if (url.startsWith("blob")) {
            Log.d("RNCWebViewManager", "Binary dowload from: " + url);
            url = url.replace("blob:","");
          } else {
            // for other unsupported protocols, just do nothing and at least AVOID CRASH
            Log.w("RNCWebViewManager", "Unsupported URL protocol: " + url);
            return;
          }
        }

        webView.setIgnoreErrFailedForThisURL(url);
       ...
       ... // existing code 
       ...
	   }

**Comment by karthikiyengar** [comment]
@twisger - I was wondering if this is something that is still being worked upon? 

@jamonholmgren, @jasongaare - The other promising PR that might help mitigate the crash seems to be https://github.com/react-native-webview/react-native-webview/pull/1546 - I was wondering what direction we intend to move in?

Happy to help on either front!

**Comment by avinashsahoo** [comment]
**Android:**

I've just fixed the issue, by putting a if condition before DownloadManager.Request. If the Url contains "blob", then it'll simply ignore. At least it will prevent crashing the app on android.

        if(!url.contains("blob"))

**iOS** 

It's anyway handling by onShouldStartLoadWithRequest.

        onShouldStartLoadWithRequest={(req) => { 
          if (req.url.startsWith("blob")) { 
            alert("Files can't be downloaded.");
            return false; 
          } 
            return true; 
          }
        }

**Comment by twisger** [comment]
> @twisger - I was wondering if this is something that is still being worked upon?
> 
> @jamonholmgren, @jasongaare - The other promising PR that might help mitigate the crash seems to be #1546 - I was wondering what direction we intend to move in?
> 
> Happy to help on either front!
> 
> P.S: I have opened #2323 that fixes the crash too.

@karthikiyengar 
I tried to make it can be downloaded successfully in android, it almost worked, But I encountered some difficulty when getting the file extension of the blob link. Feel free to send another pr about it.

**Comment by hypnocill** [comment]
@twisger do you have an example or idea how can I utilize the blob url passed to onDownloadUnsupportedUrl so that I can either open the file or download it? That would be really helpful if you do.
Thank you!

**Comment by twisger** [comment]
> @twisger do you have an example or idea how can I utilize the blob url passed to onDownloadUnsupportedUrl so that I can either open the file or download it? That would be really helpful if you do. Thank you!

This PR is not fully implemented and merged because of some difficulties of getting file extension of blob link file. But the main part is already included in the code of this pr. You can view file change of this pr and implement by yourself if you only want to support specific file type. The main step is:
1.Add a event to pass blob link to js webview.
2.Download this link in js webview and pass the blob data to native layer through event.
3.Download the blob data in native layer

**Comment by hypnocill** [comment]
@twisger I checked the diff, hopefully the injected js on blob url download will work out. I'll patch it locally. Thanks!

**Comment by hypnocill** [comment]
@twisger I patched the lib locally and it works perfectly fine with PDF from the server - it downloads it (can't open it but I don't need to). The other case I have to handle though, is when the server responds with SVG, not PDF. In this case, it doesn't work and the "window._ReactNativeWebView.downloadDataURL(dataURL)" function is never called.
I suspected it was due to "xhr.responseType = 'blob'" working only for PDF but not SVG though I tried it with 'arraybuffer', 'text' and 'document' without success.

**Comment by twisger** [comment]
> @twisger I patched the lib locally and it works perfectly fine with PDF from the server - it downloads it (can't open it but I don't need to). The other case I have to handle though, is when the server responds with SVG, not PDF. In this case, it doesn't work and the "window._ReactNativeWebView.downloadDataURL(dataURL)" function is never called. I suspected it was due to "xhr.responseType = 'blob'" working only for PDF but not SVG though I tried it with 'arraybuffer', 'text' and 'document' without success.
> 
> Do you have any idea how to make this work with SVG? Thank you!
window._ReactNativeWebView.downloadDataURL, try to check if the request is callled sucessfully. It may be refused by server because of some reason, such as the responseType is not correct. Mabe `image/svg+xml` can works.

**Comment by hypnocill** [comment]
@twisger I assume that the request is rejected for some reason, possibly due to response type but I tried all values  from https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType and still no result. Is image/svg+xml  valid response type?
Unfortunately it's very difficult for me to test and debug it because the react-native-webview lib is not directly inside my app but inside other app (Jitsi sdk) that's inside my app and one build of both projects so that I can run my code once takes a lot of time.

**Pull request closed without merging**
