### PR TITLE
fix(iOS): Implement `[RCTConvert WKDataDetectorTypes:]`

### PR DESCRIPTION
**Pull request by Saadnajmi**
Fixes https://github.com/react-native-webview/react-native-webview/issues/3426

In React Native 0.74+, https://github.com/facebook/react-native/commit/452bf0ff069b77fc880c57fcb86dbe44ac7285fc removes `[RCTConvert WKDataDetectorTypes:]` from `RCTConvert`. To fix this, let's implement the method ourselves. It's more or less a copy of the original implementation, except I made the default value `WKDataDetectorTypeNone` instead of `WKDataDetectorTypePhoneNumber`

### CODE REVIEW

**Comment by fahry-mohammed** [comment]
Any update on this?

**Comment by got2golfxx** [comment]
I am very new to all this.
I tried the workaround now I get "No +[RCTConvert WKDataDetectorTypes:] function found."

**Comment by Stuartwastaken** [comment]
This branch does not fix the issue for my project. react-native-webview still throws the error "No +[RCTConvert WKDataDetectorTypes:] function not found."

 "react-native-webview": "github:Saadnajmi/react-native-webview#datadetector",
 "react-native": "^0.74.2",
  "react-native-pell-rich-editor": "^1.9.0",
  "expo": "51.0.14"

**Comment by Saadnajmi** [comment]
The impression I'm getting id that applying my PR as a patch with setups involving expo takes more steps. I think this PR is still the correct fix for the issue. @Titozzz any chance you could take a look soon?

**Review by Titozzz — APPROVED** [review]

**Pull request merged**
