### PR TITLE
Bugfix for Unknown URL Scheme in Android

### PR DESCRIPTION
**Pull request by lrusso**
**Bugfix for "Unknown URL Scheme" error in Android.**

In the demo code below, I'm using the **nativejstn** scheme as an example, it could be anything. The custom URL scheme must be added into the **originWhitelist** array in order to work.

````javascript
const _onShouldStartLoadWithRequest = (request) => {
    if (request.url.indexOf('http') === 0) {
        return true
        } else if (request.url.indexOf('nativejstn') === 0) {
        console.log(request.url)
        }
    return false
}

return (
    <View style={{width:'100%',height:'100%'}}>
        <WebView
            source={{ uri: 'https://www.example.com' }}
            onShouldStartLoadWithRequest={_onShouldStartLoadWithRequest.bind(this)}
            originWhitelist={[
                    'https://*',
                    'http://*',
                    'nativejstn://*',
                    'about:*',
                ]}
            />
        </View>
    )
````

### CODE REVIEW

**Comment by TheAlmightyBob** [comment]
@lrusso It's not clear to me what bug this is supposed to fix or how it fixes it? Is there an open issue that discusses the problem?

**Comment by lrusso** [comment]
I found out that increasing that delay makes the URL schemes to work in Android. Otherwise, you get the ERR_UNKNOWN_URL_SCHEME message in the WebView.

https://github.com/react-native-webview/react-native-webview/issues/1719
https://github.com/react-native-webview/react-native-webview/issues/1135

**Comment by whitefang57** [comment]
@lrusso does increasing that timeout fix the issue in most cases? I'm running into a similar issue and would love a potential fix

**Comment by lrusso** [comment]
Yes, it works with all Android devices. Increase the timeout if you see that in some device is not working. It is the only way to fix this issue.

**Pull request closed without merging**
