### PR TITLE
 [iOS] Send cookies with resource requests

### PR DESCRIPTION
**Pull request by nikitawani07**
To attach cookie with all resource requests for the page loaded

**Summary**

- This PR solves this feature request #1875
- Issue: Currently, the cookies are added for page load request if custom cookies are passed in the webview source headers but they are not added for resource requests.
- How did you implement the solution?
I implemented this solution by adding cookies in webview configuration so that cookies will be send in resource requests as well.
- What areas of the library does it impact?
RNCWebView

### CODE REVIEW

**Comment by nikitawani07** [comment]
@Titozzz @jamonholmgren Could you please take a look and review it?

**Comment by nikitawani07** [comment]
@Titozzz  @jamonholmgren Requesting for review.

**Comment by Titozzz** [comment]
Could this be a security issue ? (Leaking cookies to unknown sources)

**Comment by nikitawani07** [comment]
> Could this be a security issue ? (Leaking cookies to unknown sources)

The cookie passed via webview headers is saved in webview configuration and against that particular url domain. 
The cookies available in cookie storage are added in webview configuration during webview initialisation. Similarly, the cookie is added in this case also.
I do not see any security issue as such. Let me know if there is any.

**Comment by nikitawani07** [comment]
@Titozzz Gentle reminder

**Review by Titozzz — APPROVED** [review]

**Comment by Titozzz** [comment]
I don't have the time to test it so I'll trust you on that

**Pull request merged**
