### PR TITLE
Apple Pay support in iOS

### PR DESCRIPTION
**Pull request by netmaxt3r**
Add new prop `enableApplePay` for ios which disables script injection and allow Websites to invoke Apple Pay api.
This comes with a cost features like script injection,html5 History , shared Cookies, atEndScript , atStartScript will not work
[Apple Documentation](https://developer.apple.com/documentation/safari-release-notes/safari-13-release-notes#Payment-Request-API). We can still use postMessage provided  `window.postMessage` wont work `window.webkit.messageHandlers.ReactNativeWebView.postMessage` will work

possible fix for #920

### CODE REVIEW

**Comment by TheAlmightyBob** [comment]
Minor detail, but "compact" makes me think of visual layout rather than featureset. Perhaps something like `applePayRestrictedMode` would be more clear?

**Comment by netmaxt3r** [comment]
@TheAlmightyBob   would `applePayRestrictedMode`  hints "apple Pay" is restricted, i will change this prop name to simple `enableApplePay`

**Comment by TheAlmightyBob** [comment]
> `applePayRestrictedMode` hints "apple Pay" is restricted

Yeah, that's fair. Naming is hard.

Could you update https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md?

**Review by TheAlmightyBob — APPROVED** [review]

**Comment by chuanxie** [comment]
Hi @netmaxt3r when i run the following example code, i am still get `your browser does not support apple pay on the web`, do you have any ideas? or something need to be addressed? thanks
   
```
<WebView
   enableApplePay={true}
   source={{uri: "https://applepaydemo.apple.com/"}} 
    automaticallyAdjustContentInsets={false}>
```
I am using the expo 41 and latest react native webview on 11.6.1

**Comment by chuanxie** [comment]
Screenshot 2021-05-24 at 14 54 29
so apple pay works on pure react native but not expo @netmaxt3r

**Comment by netmaxt3r** [comment]
@chuanxie  I do not have hands on with expo. All this patch does is remove script injection in webview, are you injecting any script in your webview?. let me take look at expo 41 let you know

**Comment by netmaxt3r** [comment]
@chuanxie since this change has native code changes and expo 41 has bundled [react-native-webview 11.2.3](https://github.com/expo/expo/blob/master/CHANGELOG.md#4100--2021-03-10) this wont be possible in a "managed" workflow. However in "bare" workflow use react-native-webview@11.6.0 up ( default is 11.2.3 ) it is working.

**Comment by chuanxie** [comment]
thanks @netmaxt3r  . no,  i didnt inject any scripts. just the braintree payment iframe from my web page.
hmm.. i forced the expo to use the react-native-webview@11.6.1 and its not complaining about it

**Comment by Titozzz** [comment]
It's not complaining but it wont work either because the native code just isn't here!

**Pull request merged**
