### PR TITLE
iOS: Fix webview not loading in background tab

### PR DESCRIPTION
**Pull request by sjransom**
Initial issue here: https://github.com/react-native-webview/react-native-webview/issues/2431#issuecomment-1203646983
Fix reference from: https://github.com/react-native-webview/react-native-webview/pull/1852#issuecomment-1120470181

This fixes the issue where the web view is not loaded during initial app render when it is on a separate tab.

Testing using:
`"react-native": "0.68.2"`
`"react-native-webview": "11.21.1"`

Thanks to @gbhrdt and @goleary

### CODE REVIEW

**Review by walterholohan — APPROVED** [review]

**Comment by finalight** [comment]
So what else do we need to move forward with this ?

**Comment by walterholohan** [comment]
@finalight we need a maintainer to review

@Titozzz @jamonholmgren would you be able to review please?

**Comment by TheAlmightyBob** [comment]
This makes sense _to me_.... it seems _potentially_ breaking, but I can't think of a scenario where that would matter... I suppose if folks didn't want their WebViews to load on background tabs they wouldn't set `lazy=false`... and `removeFromSuperview` is already used so there's some symmetry there...

Was `didMoveToWindow` not being called, or was the problem just that `self.window` was `nil`?

I'm a little hesitant only because the previous logic seems like it was there for a reason (i.e. the fact that it's both using `didMoveToWindow` _and_ checking `self.window`). @jamonholmgren I don't suppose you recall why it was done that way?

**Comment by owen12ab** [comment]
Any update on this?

**Comment by jamonholmgren** [comment]
Still on our list to review. Thanks for your patience!

**Comment by Faradey27** [comment]
Small note about a potential issue that we noticed.
In case if render webview in the background and webview contains  that uses srcSet  - sometimes img will not be rendered

**Comment by dvlkv** [comment]
@jamonholmgren
Hello, is there any activity on this or it is considered as stale?

**Comment by TheAlmightyBob** [comment]
This needs to be updated for compatibility with the new architecture changes. It should be pretty simple though, as it was a small change and the issue is just that the file was renamed, but it's not something that GitHub can resolve.

**Comment by Titozzz** [comment]
Closing in favor of #2930

**Comment by TheAlmightyBob** [comment]
Oh, thanks @Titozzz , I totally missed that there was an updated version.

**Pull request closed without merging**
