### PR TITLE
Fix Android full screen video when in modals

### PR DESCRIPTION
**Pull request by cristianoccazinsp**
Using a WebView within a Modal component causes a bunch of issues when trying to play video in full screen mode in Android when using `allowsFullscreenVideo={true}`.

This PR improves the View hierarchy handling to check for a Modal or differences in the root view in order to correctly decide which View to hide when playing video in full screen.

The change should be fully compatible with current usages.

Should fix: https://github.com/react-native-webview/react-native-webview/issues/1293

### CODE REVIEW

**Comment by cristianoccazinsp** [comment]
@Titozzz  this change only affects Android, can you review the Windows CI tests that are failing?

**Review by Titozzz — APPROVED** [review]

**Comment by cristianoccazinsp** [comment]
Can we release this already? What's missing?

**Comment by cristianoccazinsp** [comment]
Is there anything missing in order to release this?

**Comment by cristianoccazinsp** [comment]
Still waiting for this to be merged. Been using it for a while and no issues so far.

**Review by jamonholmgren — APPROVED** [review]
Thank you! This looks great.

**Pull request merged**
