### PR TITLE
fix(ios): Fix webview not loading in background

### PR DESCRIPTION
**Pull request by sheat-git**
Hi there!

Sorry for the lack of details in this PR. I'm not great with English, and this is my first time with Objective-C. This change is related to issues we've been discussing.

Feel free to ask questions or suggest changes. I'm open to any feedback and eager to learn.

---

PRs:
- https://github.com/react-native-webview/react-native-webview/pull/2930
- https://github.com/react-native-webview/react-native-webview/pull/3041

Issues:
- https://github.com/react-native-webview/react-native-webview/issues/2431
- https://github.com/react-native-webview/react-native-webview/issues/3481

### CODE REVIEW

**Review by jamonholmgren — APPROVED** [review]
Looks reasonable.

**Comment by ignaciosantise** [comment]
@sheat-git @jamonholmgren could it be that this change created a regression?

https://github.com/react-native-webview/react-native-webview/issues/3595
https://github.com/react-native-webview/react-native-webview/issues/3578

**Comment by aderiushev** [comment]
@ignaciosantise i'm more than sure, 13.12.2 works fine however my webpage with a js widet is now not loading (blank screen)
in console i got smth about "Failed to resolve host network", please do the rollback or fix it properly, it is a breaking regress one

**Comment by inkless** [comment]
I am seeing regression on my side as well, also more issues were seen:
https://github.com/react-native-webview/react-native-webview/issues/3612

Could we consider a revert or a proper fix?

**Comment by mlazari** [comment]
This patch that comments out the new `didMoveToSuperview` method fixes my issue (but I assume re-introduces the issue that was fixed here?):
[react-native-webview+13.12.4.patch](https://github.com/user-attachments/files/17937022/react-native-webview%2B13.12.4.patch)
```
diff --git a/node_modules/react-native-webview/apple/RNCWebViewImpl.m b/node_modules/react-native-webview/apple/RNCWebViewImpl.m
index 97d9780..16704c2 100644
--- a/node_modules/react-native-webview/apple/RNCWebViewImpl.m
+++ b/node_modules/react-native-webview/apple/RNCWebViewImpl.m
@@ -565,14 +565,14 @@ - (void)initializeWebView
 }
 
 // react-native-mac os does not support didMoveToSuperView
-#if !TARGET_OS_OSX
-- (void)didMoveToSuperview
-{
-  if (self.superview != nil && _webView == nil) {
-    [self initializeWebView];
-  }
-}
-#endif // !TARGET_OS_OSX
+// #if !TARGET_OS_OSX
+// - (void)didMoveToSuperview
+// {
+//   if (self.superview != nil && _webView == nil) {
+//     [self initializeWebView];
+//   }
+// }
+// #endif // !TARGET_OS_OSX
 
 - (void)didMoveToWindow
 {
```

**Pull request merged**
