### PR TITLE
chore(deps): bump react-native-macos to 0.62

### PR DESCRIPTION
**Pull request by tido64**
Bump react-native-macos to 0.62 to align with react-native and react-native-windows.

Screenshot:
Screenshot 2022-01-07 at 00 03 48

### CODE REVIEW

**Comment by tido64** [comment]
@Titozzz: Can you have a look when you have time? Thanks 😄

**Review by Titozzz — APPROVED** [review]

**Comment by Titozzz** [comment]
Chore won't trigger a new release, is it intended @tido64 ?

**Comment by tido64** [comment]
> Chore won't trigger a new release, is it intended @tido64 ?

Yes, this only changes devDependencies and should not affect consumers.

**Comment by tido64** [comment]
@Titozzz: Can we get this merged now? I think next, we should bump everything to 0.66.

**Pull request merged**
