### PR TITLE
fix iOS injectedJavaScriptBeforeContentLoaded

### PR DESCRIPTION
**Pull request by kevinvangelder**
This PR fixes iOS injectedJavaScriptBeforeContentLoaded to correctly update the injected javascript when the provided props change.

### CODE REVIEW

**Comment by jamonholmgren** [comment]
I think this is headed the right direction!

Talking with @Titozzz about it right now.

Couple things we'll want to see for sure:

1. Update [Guide](https://github.com/react-native-webview/react-native-webview/blob/681aac4fe7e35834264daa01b67a9893c4a9ebe7/docs/Guide.md?plain=1#L339), including a good solid example of how to use the JS object
2. Update [other docs](https://github.com/react-native-webview/react-native-webview/blob/681aac4fe7e35834264daa01b67a9893c4a9ebe7/docs/Reference.md?plain=1#LL193C17-L193C17) as necessary, including adding the JS object thing

(These were just 2 I found with a quick search.)

**Comment by kevinvangelder** [comment]
@Titozzz any feedback on this PR? I need to incorporate it in an app later this week and would love to move forward or update it with any feedback ASAP.

**Comment by Titozzz** [comment]
@kevinvangelder if it is due this week, you should use patch package for your needs. I do not have a lot of bandwidth this week

**Comment by kevinvangelder** [comment]
@Titozzz Thanks for letting me know.

**Comment by kevinvangelder** [comment]
@Titozzz It does appear that it should, but in my tests changing the value of `injectedJavaScriptBeforeContentLoaded` and then reloading the page does not result in the updated code being run on the webview. After my changes, it does.

**Pull request closed without merging**
