### PR TITLE
Incognito bugfix, clearCache on iOS and clear cookies on both platforms

### LINKED ISSUE #1143: incognito property does not respond to false or null
**Bug description:**
When setting the incognito property to false or null the webview acts as if incognito is true. At least cookies are not remembered. When setting incognito to undefined it works as expected. 

**To Reproduce:**
 ```
           <WebView
              source={{ uri: urlwithcookies }}
              sharedCookiesEnabled={true}
              incognito={false}
            />
```

**Expected behavior:**
When incognito is set to false or null it remembers my cookies. 

**Environment:**
 - OS: Tested on android
 - OS version: -
 - react-native version: 0.60.5
 - react-native-webview version: 8.0.3

### LINKED ISSUE #1296: Cookies cleared when property incognito is false
On Android cookies always deleted regardless of incognito is true or false.

**To Reproduce:**
```
<WebView
source={{uri: 'https://google.com'}}
incognito={false}
/>
```

**Expected behavior:**
When prop incognito is `false` cookies are not cleared and cache not removed.

**Screenshots/Videos:**

**Environment:**
 - OS: Android
 - OS version: Android 9
 - react-native version: 0.62.0
 - react-native-webview version: 9.0.2

### PR DESCRIPTION
**Pull request by pdandradeb**
# Summary

Problems related to cache and cookies are common and these commits aim to improve the code parity between the platforms and add a easy way to remove cookies from the Webview;

- Fixes an incognito bug in Android that clears all data when incognito={false} as was reported in a few issues (Closes #1143, Closes #1296, Suggest a new approach for #1447)
- Adds iOS support for `clearCache` (which was previously supported only in Android);
- Creates a method `clearCookies` working in both iOS and Android;

### What's required for testing (prerequisites)?

1. Pull the changes;
2. Reinstall Pods. Easy way: cd example/ios && rm -rf Pods && pod install
3. Rebuild JS. Easy way: rm -rf lib; yarn build

### What are the steps to reproduce (after prerequisites)?

1. Change the uri to a page that use cookies and reload to make sure cookies are being used.
2. Change the `incognito` property to `true`; reload;
3. Verify that cookies are not being used;
4. Change the `incognito` property back to `false`; reload;
5. Verify on iOS: cookies are being used again; on Android: cookies were clean but can be used again;
6. Click on the 'Clear Cookies' button and verify that cookies were cleared;
7. Click on the 'Clear Cache' button and verify that data was cleared;

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |      ✅     |
| Android |      ✅     |

## Checklist

- [X] I have tested this on a device and a simulator
- [X] I added the documentation in `Reference.md` and `Guide.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [X] I updated the typed files (TS and Flow)
- [X] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by rodrigomurta** [comment]
This PR will be very useful. Thanks @pdandradeb for the submission 👍🏻

**Comment by pdandradeb** [comment]
hey @jamonholmgren could you take a look at this PR? thanks!

**Comment by jmurob** [comment]
Hello Predo  @pdandradeb , I download your PR and run (cd example/ios && rm -rf Pods && pod install and rm -rf lib; yarn build) after that I remplace the lib folder on my node_modules/react-native-webview/lib , this is the correct way to test it ?, I am working in a expo managing project , but I still get the cookie error on IOS ,   thanks in avance.

**Comment by TheAlmightyBob** [comment]
I'm a little confused that this says it "Closes #1447", but #1447 is itself a PR that has already been merged to fix the Android incognito bug.

**Comment by pdandradeb** [comment]
Hey @TheAlmightyBob, you're right. I was working on it and by the time I committed, It was already closed. I've just updated the description.

The implementation is different, though. I'm calling `clearCookies` when `incognito` is enabled to create an escape hatch to making clearing cookies possible.

**Pull request closed without merging**
