### PR TITLE
feat: add loadUrl and support "about:blank" on iOS

### PR DESCRIPTION
**Pull request by sunnylqm**

### CODE REVIEW

**Comment by TheAlmightyBob** [comment]
What is the purpose of this?

**Comment by sunnylqm** [comment]
1. To make iOS and android consistent (android already supports this)
2. A controlled webview is easy to use but hard to control. sometimes you need to use it imperatively instead of props which would cause other side effects (re-renders, duplicated events, re-callbacks)

**Comment by TheAlmightyBob** [comment]
> android already supports loadUrl

Interesting... I don't think that was actually intentional, it looks like it was accidentally exposed during refactor... I wonder if there are side-effects to using that, e.g. whether all the events still work as expected...

**Comment by sunnylqm** [comment]
I am writing a basic browser and `loadUrl` works fine on both ends

**Comment by TheAlmightyBob** [comment]
Okay, I played with this briefly and didn't see any obvious issue (which still surprises me... since Android invokes `loadUrl` in the callback of `onShouldStartLoadWithRequest`, I thought that meant invoking `loadUrl` directly would bypass that event... but it still seemed to work).

Please update the docs to include the new method (though preferably pointing out that the `source` property is still the primary/recommended/supported way to set the URL), otherwise this looks okay to me.

**Comment by TheAlmightyBob** [comment]
Er, did you mean to merge #2640 into this PR?

**Comment by sunnylqm** [comment]
sorry i'll make a new pr

**Comment by sunnylqm** [comment]
https://github.com/react-native-webview/react-native-webview/pull/2736

**Pull request closed without merging**
