### PR TITLE
Enable webview to open new window on IOS

### PR DESCRIPTION
**Pull request by hlta**

### CODE REVIEW

**Comment by TheAlmightyBob** [comment]
What's the difference between this and #2189?

**Comment by hlta** [comment]
> What's the difference between this and #2189?

This is for open a new webview when target="blank" same behaviour like Android which has already been supported  but #2189 is open in external browser

**Comment by nantianyishao** [comment]
great!!!!!!

**Comment by TheAlmightyBob** [comment]
Looks like this PR now contains a bunch of unrelated Android changes, I'm guessing because you created it off of your master branch instead of a dedicated feature branch.

**Comment by hlta** [comment]
> Looks like this PR now contains a bunch of unrelated Android changes, I'm guessing because you created it off of your master branch instead of a dedicated feature branch.

Created the branch just for this fix
https://github.com/react-native-webview/react-native-webview/pull/2346

**Pull request closed without merging**
