### PR TITLE
Update kotlin version to 1.6.20

### PR DESCRIPTION
**Pull request by humarkx**
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.

### CODE REVIEW

**Review by TheAlmightyBob — APPROVED** [review]

**Comment by nateshmbhat** [comment]
when can this be merged ? its blocking all RN apps with 0.71.1 version

**Comment by TheAlmightyBob** [comment]
How is this related to React Native 0.71? I'm able to build & run a 0.71.1 app with the current version of `react-native-webview` without issue, and @Titozzz has been working with 0.71 for some time on the new architecture branch, which doesn't have this change.

Though that's possibly because our apps aren't using `kotlin-android-extensions`, which has been [discontinued](https://android-developers.googleblog.com/2022/02/discontinuing-kotlin-synthetics-for-views.html)?

I've also seen [reports](https://github.com/mrousavy/react-native-vision-camera/issues/1431#issuecomment-1404738037) that setting the Kotlin version in your own app's `build.gradle` should get around the error.

**Comment by ajp8164** [comment]
> How is this related to React Native 0.71? I'm able to build & run a 0.71.1 app with the current version of `react-native-webview` without issue, and @Titozzz has been working with 0.71 for some time on the new architecture branch, which doesn't have this change.
> 
> Though that's possibly because our apps aren't using `kotlin-android-extensions`, which has been [discontinued](https://android-developers.googleblog.com/2022/02/discontinuing-kotlin-synthetics-for-views.html)?
> 
> I've also seen [reports](https://github.com/mrousavy/react-native-vision-camera/issues/1431#issuecomment-1404738037) that setting the Kotlin version in your own app's `build.gradle` should get around the error.

Yes.  I added the following to build.gradle to fix this problem.

```
buildscript {
    ext {
        ...
        kotlinVersion = '1.7.21'
    }
}
```

**Comment by dyegolara** [comment]
Was this solved?

**Comment by cparello** [comment]
these changes are still not in master, gradle.properties in master for kotlin is 1.6


The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':react-native-webview' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0

**Comment by cparello** [comment]
Use patch package, i just ran into this last week.

Lookin webview package and find the kotlin ver ave update it then create a patch

**Comment by BogdanRad** [comment]
thank you @cparello !

**Comment by BogdanRad** [comment]
@cparello can you send me your patch? I created a patch for webview but I have this error...
image

**Comment by cparello** [comment]
diff --git a/node_modules/react-native-webview/android/gradle.properties b/node_modules/react-native-webview/android/gradle.properties
index c17e066..bc42397 100644
--- a/node_modules/react-native-webview/android/gradle.properties
+++ b/node_modules/react-native-webview/android/gradle.properties
@@ -1,4 +1,4 @@
-ReactNativeWebView_kotlinVersion=1.6.0
+ReactNativeWebView_kotlinVersion=1.6.21
 ReactNativeWebView_webkitVersion=1.4.0
 ReactNativeWebView_compileSdkVersion=31
 ReactNativeWebView_targetSdkVersion=31


copy paste into /patches filename react-native-webview+12.0.2.patch

**Comment by kukokp** [comment]
Made my days.
I spend some time on this, but finally found the solution. Thanks

**Pull request closed without merging**
