### PR TITLE
feat(macos, ios) Allow to autoselect client certificate

### PR DESCRIPTION
**Pull request by vahagnni**
WKWebView does not have a certificate picker, and there's no way to autoselect a certificate based on the requested certificate-issuing authorities.
With new flag we will be able to enable the auto-selection of certificates based on distinguishedNames. If there are multiple certificates that pass the filter, the first one will be selected.

### CODE REVIEW

**Comment by vahagnni** [comment]
@Titozzz can I get this rewiewed, thanks.

**Comment by vahagnni** [comment]
@Titozzz @jamonholmgren Can i get this reviewed thanks.

**Comment by Titozzz** [comment]
I'll try to review / merge soon ❤️

**Comment by ehtisham-ali-emumba** [comment]
@Titozzz did you get a chance to review this PR.

**Pull request closed without merging**
