### PR TITLE
fix(iOS): sync cookies obtained in WKWebView to sharedHTTPCookieStorage

### PR DESCRIPTION
**Pull request by forsen**
# Summary
In our app the authentication is completed inside a WebView. All other interactions with the backend is using the native `fetch` implementation. When using UIWebView, all cookies obtained in the WebView was stored in `sharedHTTPCookieStorage`, making them available to the native `fetch` implementation. After upgrading to `react-native-webview` >= 7.x `fetch` could no longer find the cookies obtained in the WebView when using simulator. For some reason it still works on device. 

The changes in this PR copies all cookies from `WKWebView` to `sharedHTTPCookieStorage` when `sharedCookiesEnabled` property is set on the `WebView` component.  

The following comments in #312 describes the same issue, and should be resolved with this PR.

https://github.com/react-native-community/react-native-webview/issues/312#issuecomment-498774707
https://github.com/react-native-community/react-native-webview/issues/312#issuecomment-551300898
https://github.com/react-native-community/react-native-webview/issues/312#issuecomment-555489505

### What's required for testing (prerequisites)?

- iOS simulator
- A website that sets a cookie

### What are the steps to reproduce (after prerequisites)?
- Visit website that sets a cookie using the WebView
- Inspect `sharedHTTPCookieStorage` 

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅  |
| Android |   N/A  |

## Checklist

- [X] I have tested this on a device and a simulator

### CODE REVIEW

**Comment by jamonholmgren** [comment]
@forsen I feel like this should maybe be behind a prop option. What do you think?

**Comment by jamonholmgren** [comment]
@forsen So this just fixed the simulator then?

**Comment by forsen** [comment]
At least in my use case, it does. 

During onboarding the user must obtain a cookie through a webview that must be used on all calls to our API (using `fetch`). 

This works fine on device, but stopped working on simulator with the transition from UIWebView to WKWebView.

With the fix in this PR it works fine both on device and on simulator in our case.

**Comment by jamonholmgren** [comment]
Can you resolve conflicts, @forsen?

**Comment by forsen** [comment]
Sorry about the delay, being busy having summer vacation. All conflicts are resolved.

**Comment by nspector** [comment]
Any updates on this potentially getting merged?

**Comment by jamonholmgren** [comment]
@nspector Probably in the next round of updates we publish -- within a month.

**Comment by Tordensky** [comment]
> @nspector Probably in the next round of updates we publish -- within a month.

Any updates on when this will be merged?

**Comment by Tordensky** [comment]
> Hello 👋, this PR has been opened for more than 2 months with no activity on it. If you think this is a mistake please comment and ping a maintainer to get this merged ASAP! Thanks for contributing! You have 7 days until this gets closed automatically

ping

**Comment by iGroza** [comment]
ping

**Pull request closed without merging**
