### PR TITLE
fix: cannot find `react-native-test-app` when Metro starts

### LINKED ISSUE #2430: Package react-native-webview has been ignored because it contains invalid configuration
**Bug description:**

I am trying to use react-native-webview and following step. But it doesn't work.

yarn add react-native-webview
cd ios && pod install && cd .. # CocoaPods on iOS needs this extra step

There is problem.
image

**To Reproduce:**

**Expected behavior:**

**Screenshots/Videos:**

**Environment:**
 - OS: macOS
 - OS version: 12.3
 - react-native version: 0.67.4
 - react-native-webview version: 11.18.0

### PR DESCRIPTION
**Pull request by tido64**
Resolves #2430

### CODE REVIEW

**Comment by tido64** [comment]
cc @chiaramooney

**Comment by tido64** [comment]
@chiaramooney, @Titozzz: Can you review this whenever you have time? Thanks :heart:

**Comment by tido64** [comment]
@chiaramooney, @Titozzz: Can you review this whenever you have time? Thanks :heart:

**Review by Titozzz — APPROVED** [review]

**Comment by Titozzz** [comment]
looks ok to me

**Comment by tsapeta** [comment]
Does it fix #2430? When can we expect it to be merged and released? I'm going to upgrade the library to 1.18.x for Expo SDK45 😉

**Comment by tido64** [comment]
> Does it fix #2430? When can we expect it to be merged and released? I'm going to upgrade the library in Expo to be included in SDK45 😉

It does. @Titozzz can you please merge this?

**Comment by gpbaculio** [comment]
i just upgraded and textinput closes keyboard immediately on focus?

**Pull request merged**
